#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and some have special msgs

idx=1
while [ "$idx" -le 20 ]; do
	case $idx in
        4)
            echo -e "$idx\nbad luck from China"
            ;;
        9)
            echo -e "$idx\nbad luck from Japan"
            ;;
        17)
            echo -e "$idx\nbad luck from Italy"
            ;;
        *)
            echo $idx
            ;;
    esac

    ((idx++))
done
